/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package safo.ventana;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import safo.caja.Empleado;
import safo.db.exceptions.IdNotFoundException;
import safo.db.exceptions.WrongCredentialsException;
import safo.main;
import safo.salud.Medico;
import safo.salud.Paciente;
import safo.salud.Receta;

/**
 *
 * @author Laxelott
 */
public class SAFOVentana extends javax.swing.JFrame {

    private boolean login = false;
    private DefaultListModel<String> medicamentos;

    /**
     * Creates new form SAFOVentana
     */
    public SAFOVentana() {
        initComponents();

        medicamentos = new DefaultListModel<>();
        listMedicamentos.setModel(medicamentos);
        
        txtPadecimiento.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpSaludable = new javax.swing.ButtonGroup();
        tabMain = new javax.swing.JTabbedPane();
        panelLogin = new javax.swing.JPanel();
        lblLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        panelConsulta = new javax.swing.JPanel();
        lblConsulta = new javax.swing.JLabel();
        btnConsulta = new javax.swing.JButton();
        txtConsulta = new javax.swing.JTextField();
        lblInfoConsulta = new javax.swing.JLabel();
        panelReceta = new javax.swing.JPanel();
        lblPadecimiento = new javax.swing.JLabel();
        scrollPadecimiento = new javax.swing.JScrollPane();
        txtPadecimiento = new javax.swing.JTextArea();
        lblSaludable = new javax.swing.JLabel();
        btnSaludable = new javax.swing.JToggleButton();
        llbMedicamentos = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        scrollMedicamentos = new javax.swing.JScrollPane();
        listMedicamentos = new javax.swing.JList<>();
        btnMedAdd = new javax.swing.JButton();
        btnMedDel = new javax.swing.JButton();
        lblRecetaInfo = new javax.swing.JLabel();
        btnRecetaCrear = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));
        setResizable(false);
        getContentPane().setLayout(new java.awt.FlowLayout());

        tabMain.setMinimumSize(new java.awt.Dimension(122, 100));

        panelLogin.setLayout(new java.awt.GridBagLayout());
        panelLogin.add(lblLogin, new java.awt.GridBagConstraints());

        lblUsername.setText("Nombre de Usuario:");

        lblPassword.setText("Contraseña:");

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtUsername, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(txtPassword)))
            .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(lblPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelLogin.add(jPanel2, new java.awt.GridBagConstraints());

        tabMain.addTab("Login", panelLogin);

        btnConsulta.setText("Consultar");
        btnConsulta.setActionCommand("consultar");
        btnConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaActionPerformed(evt);
            }
        });

        lblInfoConsulta.setText("ID del paciente:");

        javax.swing.GroupLayout panelConsultaLayout = new javax.swing.GroupLayout(panelConsulta);
        panelConsulta.setLayout(panelConsultaLayout);
        panelConsultaLayout.setHorizontalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConsulta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelConsultaLayout.setVerticalGroup(
            panelConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblInfoConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsulta)
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(panelConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblConsulta.getAccessibleContext().setAccessibleName("lblConsulta");
        btnConsulta.getAccessibleContext().setAccessibleName("btnConsultar");

        tabMain.addTab("Consultar Pacientes", panelConsulta);

        lblPadecimiento.setText("Padecimiento:");

        txtPadecimiento.setColumns(20);
        txtPadecimiento.setLineWrap(true);
        txtPadecimiento.setRows(5);
        scrollPadecimiento.setViewportView(txtPadecimiento);

        lblSaludable.setText("Saludable?");

        btnSaludable.setText("No");
        btnSaludable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaludableActionPerformed(evt);
            }
        });

        llbMedicamentos.setText("Medicamentos:");

        scrollMedicamentos.setPreferredSize(new java.awt.Dimension(13, 120));

        listMedicamentos.setPreferredSize(new java.awt.Dimension(10, 10));
        scrollMedicamentos.setViewportView(listMedicamentos);

        btnMedAdd.setText("Agregar");
        btnMedAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedAddActionPerformed(evt);
            }
        });

        btnMedDel.setText("Eliminar");
        btnMedDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedDelActionPerformed(evt);
            }
        });

        btnRecetaCrear.setText("Crear Receta");
        btnRecetaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecetaCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRecetaLayout = new javax.swing.GroupLayout(panelReceta);
        panelReceta.setLayout(panelRecetaLayout);
        panelRecetaLayout.setHorizontalGroup(
            panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPadecimiento)
                    .addComponent(lblSaludable)
                    .addComponent(scrollPadecimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                    .addComponent(btnSaludable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnRecetaCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(scrollMedicamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(llbMedicamentos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRecetaLayout.createSequentialGroup()
                        .addComponent(btnMedAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMedDel, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblRecetaInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtMedicamento))
                .addContainerGap())
        );
        panelRecetaLayout.setVerticalGroup(
            panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRecetaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(llbMedicamentos)
                    .addComponent(lblPadecimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRecetaLayout.createSequentialGroup()
                        .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrollMedicamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMedDel)
                            .addComponent(btnMedAdd)))
                    .addComponent(scrollPadecimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSaludable)
                    .addComponent(lblRecetaInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRecetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaludable)
                    .addComponent(btnRecetaCrear))
                .addGap(17, 17, 17))
        );

        tabMain.addTab("Generar Receta", panelReceta);

        getContentPane().add(tabMain);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaActionPerformed
        consultarPaciente();
    }//GEN-LAST:event_btnConsultaActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        login();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnSaludableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaludableActionPerformed
        if (btnSaludable.isSelected()) {
            btnSaludable.setText("Si");
        } else {
            btnSaludable.setText("No");
        }
    }//GEN-LAST:event_btnSaludableActionPerformed

    private void btnRecetaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecetaCrearActionPerformed
        generarReceta();
    }//GEN-LAST:event_btnRecetaCrearActionPerformed

    private void btnMedAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedAddActionPerformed
        medicamentos.addElement(txtMedicamento.getText());
    }//GEN-LAST:event_btnMedAddActionPerformed

    private void btnMedDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedDelActionPerformed
        if (listMedicamentos.getSelectedIndex() >= 0) {
            medicamentos.remove(listMedicamentos.getSelectedIndex());
        }
    }//GEN-LAST:event_btnMedDelActionPerformed

    /**
     * Inicia sesión
     */
    private void login() {
        String username, password;
        Empleado empleado;
        String resultado = "<html>";

        // Obtener información del usuario
        username = txtUsername.getText();
        password = txtPassword.getText();
        login = false;

        try {
            // Probar la base de datos con la información
            empleado = new Empleado(username, password.hashCode());

            // Si no mandó excepción, significa que si entró
            login = true;
            resultado += "<h3>Credenciales correctas!</h3>";
            resultado += "Nombre: " + empleado.getNombre();

        } catch (WrongCredentialsException ex) {
            resultado += "<h2>Credenciales incorrectas!</h2>";
        }

        resultado += "</html>";
        lblLogin.setText(resultado);
    }

    /**
     * Genera una receta
     */
    private void generarReceta() {
        if (login) {
            try {
                // Pide id del paciente, y te regresa sus datos
                ArrayList<String> medicamentosArray = new ArrayList();
                Medico medico = new Medico(3);
                String padecimiento;
                boolean saludable;
                int limi;

                // Obtener los datos de la receta
                padecimiento = txtPadecimiento.getText();
                saludable = btnSaludable.isSelected();

                // Obtener los medicamentos de la receta
                limi = medicamentos.getSize();
                for (int i = 0; i < limi; ++i) {
                    medicamentosArray.add(medicamentos.getElementAt(i));
                }

                // Crear la consulta y después usarla para crear la receta
                Receta receta = new Receta(
                        medico.realizarConsulta(new Paciente(4), padecimiento),
                        saludable,
                        medicamentosArray.toArray(new String[0])
                );
                // Registrar la receta en la base de datos
                receta.registrar();

                lblRecetaInfo.setText("Receta registrada!");

            } catch (IdNotFoundException ex) {
                Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            lblRecetaInfo.setText("Debes de primero haber iniciado sesión!");
        }
    }

    /**
     * Consulta un paciente
     */
    private void consultarPaciente() {
        String respuesta = "<html>";
        int id;
        int limi;
        Paciente paciente;

        if (login) {
            try {
                // Obtener la id del paciente
                id = Integer.parseInt(txtConsulta.getText());
                // Obtener los datos del paciente desde la bd
                paciente = new Paciente(id);

                respuesta += "<h1>Nombre: " + paciente.getNombre() + "</h1>"
                        + "RFC: " + paciente.getRFC() + "<br>"
                        + "Edad: " + paciente.getEdad() + "<br>"
                        + "Peso: " + paciente.getPeso() + "kg<br>"
                        + "Estatura: " + paciente.getEstatura() + "cm<br>"
                        + "Alergias: <ul>";

                limi = paciente.getAlergias().length;
                for (int i = 0; i < limi; i++) {
                    respuesta += "<li>" + paciente.getAlergias()[i] + "</li>";
                }

                respuesta += "</ul>";
            } catch (NumberFormatException ex) {
                respuesta += "<h2>La id debe de ser numérica!</h2>";
            } catch (IdNotFoundException ex) {
                respuesta += "<h2>" + ex.getMessage() + "</h2>";
            }
        } else {
            respuesta += "<h2>Tienes que iniciar sesión primero!</h2>";
        }

        respuesta += "</html>";

        lblConsulta.setText(respuesta);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SAFOVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SAFOVentana().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsulta;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMedAdd;
    private javax.swing.JButton btnMedDel;
    private javax.swing.JButton btnRecetaCrear;
    private javax.swing.JButton btnSalir;
    private javax.swing.JToggleButton btnSaludable;
    private javax.swing.ButtonGroup grpSaludable;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblInfoConsulta;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblPadecimiento;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRecetaInfo;
    private javax.swing.JLabel lblSaludable;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JList<String> listMedicamentos;
    private javax.swing.JLabel llbMedicamentos;
    private javax.swing.JPanel panelConsulta;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelReceta;
    private javax.swing.JScrollPane scrollMedicamentos;
    private javax.swing.JScrollPane scrollPadecimiento;
    private javax.swing.JTabbedPane tabMain;
    private javax.swing.JTextField txtConsulta;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextArea txtPadecimiento;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
